# fly.toml app configuration file generated for colleges-api-india on 2023-10-04T22:00:37+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "colleges-api-india"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
